/// <reference types="jest" />

import {
  validateGeneratedPython,
  hasScpiUsage,
} from './generatedCodeValidator';

describe('generatedCodeValidator', () => {
  const validSnippet = `#!/usr/bin/env python3
# Generated by TekAutomate
import pyvisa
def main():
    scpi.write("CH1:SCALE 1")
if __name__ == "__main__":
    main()
`;

  describe('validateGeneratedPython', () => {
    it('passes when all defaults and required substrings are present', () => {
      const r = validateGeneratedPython(validSnippet, {
        requiredSubstrings: ['CH1:SCALE 1', 'scpi.write'],
      });
      expect(r.valid).toBe(true);
      expect(r.errors).toHaveLength(0);
    });

    it('fails when required substring is missing', () => {
      const r = validateGeneratedPython(validSnippet, {
        requiredSubstrings: ['*IDN?'],
      });
      expect(r.valid).toBe(false);
      expect(r.errors.some((e) => e.includes('*IDN?'))).toBe(true);
    });

    it('fails when forbidden substring is present', () => {
      const r = validateGeneratedPython(validSnippet, {
        forbiddenSubstrings: ['TODO', 'FIXME'],
      });
      expect(r.valid).toBe(true);
      const withForbidden = validateGeneratedPython(validSnippet + '\n# TODO', {
        forbiddenSubstrings: ['TODO'],
      });
      expect(withForbidden.valid).toBe(false);
      expect(withForbidden.errors.some((e) => e.includes('TODO'))).toBe(true);
    });

    it('can skip default checks when options set to false', () => {
      const noShebang = 'def main(): pass\nif __name__ == "__main__":\n    main()';
      const r = validateGeneratedPython(noShebang, {
        requireShebang: false,
        requireMain: true,
        requireGeneratedBy: false,
      });
      expect(r.valid).toBe(true);
    });
  });

  describe('hasScpiUsage', () => {
    it('returns true when scpi.write or scpi.query is present', () => {
      expect(hasScpiUsage(validSnippet)).toBe(true);
      expect(hasScpiUsage('scpi.query("*IDN?")')).toBe(true);
      expect(hasScpiUsage('import pyvisa\n')).toBe(false);
    });
  });
});
