/**
 * Validates generated Python script output.
 * Used by E2E to assert exported code and can be used in-app before export
 * to warn users if generated code is missing expected content.
 */

export interface GeneratedCodeValidationOptions {
  /** All of these substrings must appear in the code. */
  requiredSubstrings?: string[];
  /** None of these substrings may appear (e.g. placeholder left in). */
  forbiddenSubstrings?: string[];
  /** Require shebang line. */
  requireShebang?: boolean;
  /** Require def main(): and if __name__ == "__main__": and main(). */
  requireMain?: boolean;
  /** Require "Generated by TekAutomate" (or similar) in comments. */
  requireGeneratedBy?: boolean;
}

export interface GeneratedCodeValidationResult {
  valid: boolean;
  errors: string[];
}

const DEFAULT_OPTIONS: Partial<GeneratedCodeValidationOptions> = {
  requireShebang: true,
  requireMain: true,
  requireGeneratedBy: true,
};

/**
 * Validate generated Python code against expectations.
 * Use this in E2E to assert exported files and in the app before export to warn users.
 */
export function validateGeneratedPython(
  code: string,
  options: GeneratedCodeValidationOptions = {}
): GeneratedCodeValidationResult {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const errors: string[] = [];

  if (opts.requireShebang && !/^#![\s\S]*?python/i.test(code)) {
    errors.push('Missing or invalid shebang (e.g. #!/usr/bin/env python3)');
  }

  if (opts.requireMain) {
    if (!/def\s+main\s*\(/m.test(code)) errors.push('Missing def main():');
    if (!/if\s+__name__\s*==\s*["']__main__["']/m.test(code)) errors.push('Missing if __name__ == "__main__":');
    if (!/\bmain\s*\(/m.test(code)) errors.push('Missing main() call');
  }

  if (opts.requireGeneratedBy && !/Generated by TekAutomate/i.test(code)) {
    errors.push('Missing "Generated by TekAutomate" in comments');
  }

  (opts.requiredSubstrings || []).forEach((sub) => {
    if (!code.includes(sub)) errors.push(`Required substring not found: "${sub}"`);
  });

  (opts.forbiddenSubstrings || []).forEach((sub) => {
    if (code.includes(sub)) errors.push(`Forbidden substring found: "${sub}"`);
  });

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Assert that code contains at least one SCPI usage (scpi.write or scpi.query).
 * Useful as a minimal sanity check when no specific commands are required.
 */
export function hasScpiUsage(code: string): boolean {
  return code.includes('scpi.write') || code.includes('scpi.query');
}
