import { promises as fs } from 'fs';
import * as path from 'path';
import { getToolRegistry, resetToolRegistry, type MicroTool } from '../src/core/toolRegistry';
import { getToolSearchEngine, resetToolSearchEngine } from '../src/core/toolSearch';
import { tekRouter, type RouterRequest } from '../src/core/toolRouter';
import { hydrateBuiltinShortcuts } from '../src/core/toolHydrator';
import { loadProviderManifests } from '../src/core/providerLoader';
import { bootRouter, getRouterHealth } from '../src/core/routerIntegration';
import { executeBuild } from '../src/core/buildAction';
import { getCommandIndex, initCommandIndex } from '../src/core/commandIndex';
import { getRagIndexes, initRagIndexes } from '../src/core/ragIndex';
import { getTemplateIndex, initTemplateIndex } from '../src/core/templateIndex';

let passed = 0;
let failed = 0;

function assert(condition: boolean, label: string): void {
  if (condition) {
    passed += 1;
    console.log(`  ok ${label}`);
  } else {
    failed += 1;
    console.log(`  not ok ${label}`);
  }
}

function makeMockTool(header: string, description: string, triggers: string[]): MicroTool {
  return {
    id: `scpi:${header}`,
    name: header,
    description,
    triggers,
    tags: ['scpi'],
    category: 'scpi_lookup',
    schema: {
      type: 'object',
      properties: {
        channel: { type: 'string', description: 'Channel' },
      },
    },
    handler: async (args) => ({
      ok: true,
      data: { header, args },
      text: `Resolved ${header}`,
    }),
    usageCount: 0,
    lastUsedAt: 0,
    autoGenerated: true,
  };
}

async function testRegistry(): Promise<void> {
  console.log('\n--- Registry Tests ---');
  const registry = resetToolRegistry();
  resetToolSearchEngine();
  registry.register(makeMockTool('CH<x>:BANdwidth', 'Set channel bandwidth cleanly', ['bandwidth']));
  registry.register(makeMockTool('TRIGger:A:EDGE:SOUrce', 'Set trigger source cleanly', ['trigger source']));
  assert(registry.size() === 2, 'registered two tools');
  assert(registry.lookupByTrigger('bandwidth').length === 1, 'trigger index resolves bandwidth');
  registry.recordUsage('scpi:CH<x>:BANdwidth');
  assert((registry.get('scpi:CH<x>:BANdwidth')?.usageCount || 0) === 1, 'usage count increments');
}

async function testSearchAndRouter(): Promise<void> {
  console.log('\n--- Search Tests ---');
  const registry = resetToolRegistry();
  const engine = resetToolSearchEngine();
  registry.register(makeMockTool('CH<x>:BANdwidth', 'Set channel bandwidth limit', ['bandwidth']));
  registry.register(makeMockTool('CH<x>:OFFSet', 'Set channel vertical offset', ['offset', 'vertical offset']));
  registry.registerBatch(hydrateBuiltinShortcuts());
  engine.rebuildIndex();

  const hits = await engine.search('vertical offset', { semanticEnabled: false });
  assert(hits.length >= 1, 'bm25 search returns results');
  assert(hits[0].tool.id === 'scpi:CH<x>:OFFSet', 'bm25 ranks offset first');

  const router = await tekRouter({ action: 'search', query: 'screenshot', debug: true });
  assert(router.ok === true, 'router search succeeds');
  assert(router.results?.[0]?.id === 'shortcut:screenshot', 'router finds screenshot shortcut');
  assert(Boolean(router.results?.[0]?.debug), 'router debug payload is included when requested');

  const exec = await tekRouter({
    action: 'exec',
    toolId: 'shortcut:measurement',
    args: { measurements: 'FREQUENCY,RMS', channel: 'CH2' },
  });
  assert(exec.ok === true, 'measurement shortcut executes');
  assert(String(exec.text || '').includes('ACTIONS_JSON'), 'measurement shortcut returns ACTIONS_JSON');

  const build = await tekRouter({
    action: 'build',
    query: 'Add frequency and amplitude measurements on CH1',
    context: {
      backend: 'pyvisa',
      deviceType: 'SCOPE',
      modelFamily: 'MSO4/5/6 Series',
      steps: [],
      alias: 'scope1',
    },
  });
  assert(build.ok === true, 'build action executes');
  assert(String(build.text || '').includes('ACTIONS_JSON'), 'build action returns ACTIONS_JSON');

  const info = await tekRouter({
    action: 'build',
    query: 'what params can I use with MEASUrement:ADDMEAS',
    context: {
      modelFamily: 'MSO4/5/6 Series',
    },
  });
  assert(info.ok === true, 'build info mode executes');
  assert(String(info.text || '').includes('MEASUrement:ADDMEAS'), 'build info mode returns command info');
}

async function testProviderLoader(): Promise<void> {
  console.log('\n--- Provider Tests ---');
  const providersDir = path.join(process.cwd(), 'providers_test_tmp');
  await fs.mkdir(providersDir, { recursive: true });
  await fs.writeFile(
    path.join(providersDir, 'demo.json'),
    JSON.stringify([
      {
        id: 'ping',
        name: 'Ping Provider',
        description: 'Provider manifest tool for smoke tests',
        triggers: ['provider ping'],
        tags: ['provider', 'ping'],
        category: 'composite',
        handlerRef: 'static_result',
        handlerConfig: { ok: true, text: 'pong', data: { pong: true } },
      },
    ]),
    'utf8'
  );

  const tools = await loadProviderManifests(providersDir);
  assert(tools.length === 1, 'provider manifest loads');
  const result = await tools[0].handler({});
  assert(result.text === 'pong', 'provider handler executes configured result');
  await fs.rm(providersDir, { recursive: true, force: true });
}

async function testBootWithRealIndexes(): Promise<void> {
  console.log('\n--- Boot Tests ---');
  resetToolRegistry();
  resetToolSearchEngine();
  await Promise.all([initCommandIndex(), initRagIndexes(), initTemplateIndex()]);
  const commandIndex = await getCommandIndex();
  const ragIndexes = await getRagIndexes();
  const templates = (await getTemplateIndex()).all().map((doc) => ({
    id: doc.id,
    name: doc.name,
    description: doc.description,
    backend: 'template',
    deviceType: 'workflow',
    tags: [],
    steps: doc.steps,
  }));

  const report = await bootRouter({ commandIndex, ragIndexes, templates });
  assert(report.total > 0, 'boot hydrates router tools');

  const health = getRouterHealth() as Record<string, unknown>;
  assert((health.loadedProviderTools as number) >= 6, 'boot loads provider tools from manifests');
  assert(((health.registrationErrors as unknown[]) || []).length >= 1, 'invalid provider tool is rejected');

  const search = await tekRouter({ action: 'search', query: 'afg burst', debug: true });
  assert(search.ok === true, 'router search works after boot');
  assert(search.results?.some((item) => item.id === 'provider:instrument-overlays:afg-burst-setup') === true, 'provider tool is searchable after boot');

  const resetFlow = await executeBuild({
    query: 'Reset scope to factory defaults',
    context: {
      backend: 'pyvisa',
      deviceType: 'SCOPE',
      modelFamily: 'MSO4/5/6 Series',
      steps: [],
      alias: 'scope1',
    },
  });
  const resetText = String(resetFlow.text || '');
  assert(resetText.includes('*RST'), 'reset flow includes *RST');
  assert(resetText.includes('*OPC?'), 'reset flow includes *OPC?');
  assert(resetText.includes('*CLS'), 'reset flow includes *CLS');
}

async function main(): Promise<void> {
  process.env.MCP_ROUTER_ENABLED = 'true';
  process.env.MCP_SEMANTIC_ENABLED = 'false';

  console.log('--- Router Smoke Test ---');
  await testRegistry();
  await testSearchAndRouter();
  await testProviderLoader();
  await testBootWithRealIndexes();

  console.log(`\n--- Results: ${passed} passed, ${failed} failed ---`);
  process.exit(failed > 0 ? 1 : 0);
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
