/**
 * Tests that verify the generated Python output for the step-based generator.
 * Failures point directly to generator changes; update expectations or fix the generator.
 */
/// <reference types="jest" />

import { generatePythonFromSteps, GeneratorStep, GeneratorConfig } from './stepToPython';

const baseConfig: GeneratorConfig = {
  backend: 'pyvisa',
  host: '192.168.1.100',
  connectionType: 'tcpip',
  timeout: 5000,
};

describe('generatePythonFromSteps', () => {
  it('generates PyVISA script with header and main', () => {
    const steps: GeneratorStep[] = [];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('#!/usr/bin/env python3');
    expect(code).toContain('Generated by TekAutomate');
    expect(code).toContain('import pyvisa');
    expect(code).toContain('import argparse, time, pathlib');
    expect(code).toContain('def main():');
    expect(code).toContain('if __name__ == "__main__":');
    expect(code).toContain('main()');
    expect(code).toContain('TCPIP::192.168.1.100::INSTR');
    expect(code).toContain('scpi.query("*IDN?")');
    expect(code).toContain('scpi.close()');
    expect(code).toContain('rm.close()');
  });

  it('emits scpi.write for a write step', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'write', label: 'Set scale', params: { command: 'CH1:SCALE 1.0' } },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('scpi.write("CH1:SCALE 1.0")');
    expect(code).toContain('log_cmd("CH1:SCALE 1.0", "")');
  });

  it('emits variable assignment for a query step with saveAs', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'query', label: 'IDN', params: { command: '*IDN?', saveAs: 'idn' } },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('idn = scpi.query("*IDN?").strip()');
    expect(code).toContain('log_cmd("*IDN?", idn)');
  });

  it('emits time.sleep for a sleep step', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'sleep', label: 'Wait', params: { duration: 0.5 } },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('time.sleep(0.5)');
  });

  it('emits comment lines for a comment step', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'comment', label: 'Note', params: { text: 'Documentation only' } },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('# Documentation only');
  });

  it('emits Python snippet with correct indentation for a python step', () => {
    const steps: GeneratorStep[] = [
      {
        id: '1',
        type: 'python',
        label: 'Custom',
        params: { code: 'print(f"IDN: {idn}")\nresult = idn.split(",")[0]' },
      },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('    print(f"IDN: {idn}")');
    expect(code).toContain('    result = idn.split(",")[0]');
  });

  it('emits set_and_query as write then query', () => {
    const steps: GeneratorStep[] = [
      {
        id: '1',
        type: 'set_and_query',
        label: 'Set and verify',
        params: {
          command: 'CH1:SCALE',
          cmdParams: [],
          paramValues: { value: '1.0' },
          saveAs: 'scale_val',
        },
      },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('scpi.write("CH1:SCALE 1.0")');
    expect(code).toContain('scale_val = scpi.query("CH1:SCALE?").strip()');
  });

  it('skips connect and disconnect steps (handled in main)', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'connect', label: 'Connect', params: {} },
      { id: '2', type: 'query', label: 'IDN', params: { command: '*IDN?', saveAs: 'idn' } },
      { id: '3', type: 'disconnect', label: 'Disconnect', params: {} },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('idn = scpi.query("*IDN?").strip()');
    expect(code).not.toMatch(/\b(connect|disconnect)\b/);
  });

  it('nested group emits group comment and child steps', () => {
    const steps: GeneratorStep[] = [
      {
        id: 'g1',
        type: 'group',
        label: 'SCPI',
        params: {},
        children: [
          { id: '1', type: 'write', label: 'W', params: { command: 'ACQ:STATE OFF' } },
          { id: '2', type: 'query', label: 'Q', params: { command: '*OPC?', saveAs: '_' } },
        ],
      },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('# Group: SCPI');
    expect(code).toContain('scpi.write("ACQ:STATE OFF")');
    expect(code).toContain('_ = scpi.query("*OPC?").strip()');
  });

  it('throws for non-pyvisa backend', () => {
    expect(() =>
      generatePythonFromSteps([], { ...baseConfig, backend: 'tm_devices' })
    ).toThrow('only supports backend "pyvisa"');
  });

  // --- Robustness: edge cases and realistic flows ---

  it('query without saveAs uses default variable name result', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'query', label: 'Q', params: { command: '*OPT?' } },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('result = scpi.query("*OPT?").strip()');
    expect(code).toContain('log_cmd("*OPT?", result)');
  });

  it('handles empty or missing params safely', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'sleep', label: 'Wait', params: {} },
      { id: '2', type: 'comment', label: 'C', params: {} },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('time.sleep(0)');
    expect(code).toContain('# C');
  });

  it('sleep with zero duration emits time.sleep(0)', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'sleep', params: { duration: 0 } },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('time.sleep(0)');
  });

  it('full sequence: write, query, sleep, write produces valid Python', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'write', label: 'Stop', params: { command: 'ACQ:STATE OFF' } },
      { id: '2', type: 'query', label: 'OPC', params: { command: '*OPC?', saveAs: '_' } },
      { id: '3', type: 'sleep', label: 'Wait', params: { duration: 0.2 } },
      { id: '4', type: 'write', label: 'Start', params: { command: 'ACQ:STATE ON' } },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('scpi.write("ACQ:STATE OFF")');
    expect(code).toContain('_ = scpi.query("*OPC?").strip()');
    expect(code).toContain('time.sleep(0.2)');
    expect(code).toContain('scpi.write("ACQ:STATE ON")');
    expect(code).toContain('if __name__ == "__main__":');
  });

  it('socket connection type produces TCPIP SOCKET resource string', () => {
    const config: GeneratorConfig = {
      ...baseConfig,
      connectionType: 'socket',
      host: '192.168.1.50',
      port: 5025,
    };
    const code = generatePythonFromSteps([], config);
    expect(code).toContain('TCPIP::192.168.1.50::5025::SOCKET');
  });

  it('set_and_query with empty paramValues still emits valid write and query', () => {
    const steps: GeneratorStep[] = [
      {
        id: '1',
        type: 'set_and_query',
        params: {
          command: 'CH1:SCALE?',
          cmdParams: [],
          paramValues: {},
          saveAs: 'scale',
        },
      },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('scpi.write("CH1:SCALE")');
    expect(code).toContain('scale = scpi.query("CH1:SCALE?").strip()');
  });

  it('returns a single string with valid structure', () => {
    const steps: GeneratorStep[] = [
      { id: '1', type: 'write', params: { command: 'ACQ:STATE OFF' } },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(typeof code).toBe('string');
    expect(code.length).toBeGreaterThan(100);
    expect(code.startsWith('#!/usr/bin/env python3')).toBe(true);
    expect(code.trim()).toContain('if __name__ == "__main__":');
    expect(code.endsWith('main()\n') || code.endsWith('main()')).toBe(true);
  });

  // --- Parameter → Python propagation (real regression) ---

  it('CH1:SCALE {scale} paramValues { scale: 1 } propagates to Python as CH1:SCALE 1', () => {
    const steps: GeneratorStep[] = [
      {
        id: '1',
        type: 'write',
        params: {
          command: 'CH1:SCALE {scale}',
          cmdParams: [{ name: 'scale', default: '1' }],
          paramValues: { scale: 1 },
        },
      },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('CH1:SCALE 1');
    expect(code).not.toContain('{scale}');
  });

  it('OUTPut{ch}:STATe {state} with paramValues propagates correctly', () => {
    const steps: GeneratorStep[] = [
      {
        id: '1',
        type: 'write',
        params: {
          command: 'OUTPut{ch}:STATe {state}',
          cmdParams: [{ name: 'ch' }, { name: 'state' }],
          paramValues: { ch: 1, state: 'ON' },
        },
      },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('OUTPut1:STATe ON');
    expect(code).not.toMatch(/scpi\.write\("[^"]*\{[a-z]+\}[^"]*"\)/);
  });

  it('no unresolved placeholders in generated write output', () => {
    const steps: GeneratorStep[] = [
      {
        id: '1',
        type: 'write',
        params: {
          command: 'CH1:SCALE {scale}',
          cmdParams: [{ name: 'scale', default: '1.0' }],
          paramValues: { scale: 2.5 },
        },
      },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('CH1:SCALE 2.5');
    expect(code).not.toContain('{scale}');
  });

  it('query step with param substitution: placeholder replaced in generated code', () => {
    const steps: GeneratorStep[] = [
      {
        id: '1',
        type: 'query',
        params: {
          command: 'CH{ch}:SCALE?',
          cmdParams: [{ name: 'ch' }],
          paramValues: { ch: 2 },
          saveAs: 'scale',
        },
      },
    ];
    const code = generatePythonFromSteps(steps, baseConfig);
    expect(code).toContain('CH2:SCALE?');
    expect(code).not.toContain('{ch}');
  });
});
