/**
 * E2E: Open app, open export modal, export Python script, intercept download
 * and assert on generated code. Saved to e2e-output/ for inspection.
 * Plan: full coverage — boilerplate + concrete SCPI; template flow → export → assert.
 */

import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { gotoBuilder } from './helpers';

const E2E_OUTPUT_DIR = path.join(process.cwd(), 'e2e-output');
const EXPORTED_SCRIPT_PATH = path.join(E2E_OUTPUT_DIR, 'exported_script.py');
const EXPORTED_WITH_TEMPLATE_PATH = path.join(E2E_OUTPUT_DIR, 'exported_with_template.py');

test.beforeAll(() => {
  fs.mkdirSync(E2E_OUTPUT_DIR, { recursive: true });
});

test('export Python script and verify generated output', async ({ page }) => {
  await gotoBuilder(page);

  await page.getByRole('button', { name: /Gen Code/i }).click();
  await expect(page.getByRole('heading', { name: /Generate Python Code/i })).toBeVisible({ timeout: 5000 });

  const downloadPromise = page.waitForEvent('download', { timeout: 15000 });
  await page.getByRole('button', { name: /Export Script|Download script/i }).click();
  const download = await downloadPromise;
  await download.saveAs(EXPORTED_SCRIPT_PATH);

  const content = fs.readFileSync(EXPORTED_SCRIPT_PATH, 'utf-8');
  expect(content).toContain('#!/usr/bin/env python3');
  expect(content).toContain('Generated by TekAutomate');
  expect(content).toContain('import pyvisa');
  expect(content).toContain('def main():');
  expect(content).toContain('if __name__ == "__main__":');
  expect(content).toContain('main()');
  expect(content.length).toBeGreaterThan(200);
  // Concrete SCPI usage: exported script must contain at least one of these (connection block or steps)
  expect(
    content.includes('scpi.write') || content.includes('scpi.query')
  ).toBe(true);
});

test('load Hello Scope template, export, and verify script contains template SCPI', async ({ page }) => {
  await gotoBuilder(page);

  // Open Templates (nav)
  await page.getByRole('button', { name: /Templates/i }).click();
  await expect(page.getByRole('heading', { name: /Templates/i })).toBeVisible({ timeout: 5000 });

  // Wait for built-in templates to load and find Hello Scope card
  const helloScopeCard = page.locator('[data-tour="hello-scope-template"]').first();
  await expect(helloScopeCard).toBeVisible({ timeout: 10000 });

  // Append as Group
  await helloScopeCard.getByRole('button', { name: /Append as Group/i }).click();
  await page.waitForTimeout(500);

  // Back to Steps (Builder) view
  await page.getByRole('button', { name: /^Steps$/i }).click();
  await page.waitForTimeout(300);

  // Gen Code → Export
  await page.getByRole('button', { name: /Gen Code/i }).click();
  await expect(page.getByRole('heading', { name: /Generate Python Code/i })).toBeVisible({ timeout: 5000 });
  const downloadPromise = page.waitForEvent('download', { timeout: 15000 });
  await page.getByRole('button', { name: /Export Script|Download script/i }).click();
  const download = await downloadPromise;
  await download.saveAs(EXPORTED_WITH_TEMPLATE_PATH);

  const content = fs.readFileSync(EXPORTED_WITH_TEMPLATE_PATH, 'utf-8');
  expect(content).toContain('*IDN?');
  expect(content).toContain('*OPT?');
  expect(content).toContain('idn');
  expect(content).toContain('options');
  // Generator uses safe_query_text() helper instead of raw scpi.query()
  expect(
    content.includes('scpi.query') || content.includes('safe_query_text')
  ).toBe(true);
});
