#!/usr/bin/env python3
"""
build_mso2_json.py
──────────────────
Builds mso2.json by filtering mso_2_4_5_6_7.json to only the commands
listed in MSO2_HEADERS below.

Usage:
    python scripts/build_mso2_json.py

Output:
    mso2.json  (same schema as mso_2_4_5_6_7.json)
    mso2_missing.txt  (headers in the list that were NOT found in source)
"""

import json, re, sys
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1: Paste the full SCPI command header list from the MSO2 manual here.
# Format: one header per line, e.g. "ACQuire:MODe" or "TRIGger:A:EDGE:SOUrce"
# Capitalisation doesn't matter — matching is case-insensitive.
# ─────────────────────────────────────────────────────────────────────────────
MSO2_HEADERS = """
ACQuire?
ACQuire:FASTAcq:PALEtte
ACQuire:FASTAcq:STATE
ACQuire:MAXSamplerate?
ACQuire:MODe
ACQuire:NUMACq?
ACQuire:NUMAVg
ACQuire:SEQuence:CURrent?
ACQuire:SEQuence:MODe
ACQuire:SEQuence:NUMSEQuence
ACQuire:STATE
ACQuire:STOPAfter
ACTONEVent:ENable
ACTONEVent:LIMit
ACTONEVent:LIMITCount
ACTONEVent:MASKFail:ACTION:SAVEIMAGe:STATE
ACTONEVent:MASKFail:ACTION:SAVEWAVEform:STATE
ACTONEVent:MASKFail:ACTION:SRQ:STATE
ACTONEVent:MASKFail:ACTION:STOPACQ:STATE
ACTONEVent:MASKHit:ACTION:SAVEIMAGe:STATE
ACTONEVent:MASKHit:ACTION:SAVEWAVEform:STATE
ACTONEVent:MASKHit:ACTION:SRQ:STATE
ACTONEVent:MASKHit:ACTION:STOPACQ:STATE
ACTONEVent:MASKPass:ACTION:SAVEIMAGe:STATE
ACTONEVent:MASKPass:ACTION:SAVEWAVEform:STATE
ACTONEVent:MASKPass:ACTION:SRQ:STATE
ACTONEVent:MASKPass:ACTION:STOPACQ:STATE
ACTONEVent:MEASUrement:ACTION:SAVEIMAGe:STATE
ACTONEVent:MEASUrement:ACTION:SAVEWAVEform:STATE
ACTONEVent:MEASUrement:ACTION:SRQ:STATE
ACTONEVent:MEASUrement:ACTION:STOPACQ:STATE
ACTONEVent:SEARCH:ACTION:SAVEIMAGe:STATE
ACTONEVent:SEARCH:ACTION:SAVEWAVEform:STATE
ACTONEVent:SEARCH:ACTION:SRQ:STATE
ACTONEVent:SEARCH:ACTION:STOPACQ:STATE
ACTONEVent:TRIGger:ACTION:SAVEIMAGe:STATE
ACTONEVent:TRIGger:ACTION:SAVEWAVEform:STATE
ACTONEVent:TRIGger:ACTION:SRQ:STATE
ACTONEVent:TRIGger:ACTION:STOPACQ:STATE
AFG:AMPLitude
AFG:ARBitrary:SOUrce
AFG:BURSt:CCOUnt
AFG:BURSt:TRIGger
AFG:FREQuency
AFG:FUNCtion
AFG:HIGHLevel
AFG:LOWLevel
AFG:NOISEAdd:PERCent
AFG:NOISEAdd:STATE
AFG:OFFSet
AFG:OUTPut:LOAd:IMPEDance
AFG:OUTPut:MODe
AFG:OUTPut:STATE
AFG:PERIod
AFG:PULse:WIDth
AFG:RAMP:SYMmetry
AFG:SQUare:DUty
ALIas
ALIas:CATalog?
ALIas:DEFine
ALIas:DELEte
ALIas:DELEte:ALL
ALIas:DELEte:NAMe
ALIas:STATE
ALLEv?
AUTOSAVEPITIMEOUT
AUTOSAVEUITIMEOUT
AUTOSet
AUTOSet:ACQuisition:ENAble
AUTOSet:ENAble
AUTOSet:HORizontal:ENAble
AUTOSet:TRIGger:ENAble
AUTOSet:VERTical:ENAble
AUTOSet:VERTical:OPTIMize
AUXout:EDGE
AUXout:SOUrce
BATTery:ACPOWer?
BATTery:SLOT<1,2>:CHARGE?
BATTery:SLOT<1,2>:INSTalled?
BATTery:SLOT<1,2>:SERIALnumber?
BATTery:SLOT<1,2>:TIMETOEMPty?
BATTery:SLOT<1,2>:TIMETOFULL?
BUS:ADDNew
BUS:B<x>:CAN:BITRate
BUS:B<x>:CAN:BITRate:VALue
BUS:B<x>:CAN:FD:BITRate
BUS:B<x>:CAN:FD:BITRate:CUSTom
BUS:B<x>:CAN:SAMPLEpoint
BUS:B<x>:CAN:SIGNal
BUS:B<x>:CAN:SOUrce
BUS:B<x>:CAN:STANDard
BUS:B<x>:CAN:THReshold
BUS:B<x>:DISplay:FORMat
BUS:B<x>:DISplay:LAYout
BUS:B<x>:I2C:CLOCk:SOUrce
BUS:B<x>:I2C:CLOCk:THReshold
BUS:B<x>:I2C:DATa:SOUrce
BUS:B<x>:I2C:DATa:THReshold
BUS:B<x>:I2C:RWINADDR
BUS:B<x>:LABel:COLor
BUS:B<x>:LABel:FONT:BOLD
BUS:B<x>:LABel:FONT:ITALic
BUS:B<x>:LABel:FONT:SIZE
BUS:B<x>:LABel:FONT:TYPE
BUS:B<x>:LABel:FONT:UNDERline
BUS:B<x>:LABel:name
BUS:B<x>:LABel:XPOS
BUS:B<x>:LABel:YPOS
BUS:B<x>:LIN:BITRate
BUS:B<x>:LIN:BITRate:CUSTom
BUS:B<x>:LIN:IDFORmat
BUS:B<x>:LIN:POLarity
BUS:B<x>:LIN:SAMPLEpoint
BUS:B<x>:LIN:SOUrce
BUS:B<x>:LIN:SOUrce:THReshold
BUS:B<x>:LIN:STANDard
BUS:B<x>:PARallel:ALLTHResholds
BUS:B<x>:PARallel:ALLTHResholds:APPly
BUS:B<x>:PARallel:BIT<x>SOUrce
BUS:B<x>:PARallel:BIT<x>SOUrce:THReshold
BUS:B<x>:PARallel:CLOCk:EDGE
BUS:B<x>:PARallel:CLOCk:ISCLOCKED
BUS:B<x>:PARallel:CLOCkSOUrce
BUS:B<x>:PARallel:CLOCkSOUrce:THReshold
BUS:B<x>:RS232C:BITRate
BUS:B<x>:RS232C:BITRate:CUSTom
BUS:B<x>:RS232C:DATABits
BUS:B<x>:RS232C:DELIMiter
BUS:B<x>:RS232C:DISplaymode
BUS:B<x>:RS232C:PARity
BUS:B<x>:RS232C:POLarity
BUS:B<x>:RS232C:SOUrce
BUS:B<x>:RS232C:SOUrce:THReshold
BUS:B<x>:SENT:CHANWidth
BUS:B<x>:SENT:NIBBLECount
BUS:B<x>:SENT:NUMCHANnel
BUS:B<x>:SENT:PAUSEPULSe
BUS:B<x>:SENT:POLARITY
BUS:B<x>:SENT:SLOW
BUS:B<x>:SENT:SOUrce
BUS:B<x>:SENT:THRESHold
BUS:B<x>:SENT:TICKTIME
BUS:B<x>:SENT:TICKTOLerance
BUS:B<x>:SPI:BITOrder
BUS:B<x>:SPI:CLOCk:POLarity
BUS:B<x>:SPI:CLOCk:SOUrce
BUS:B<x>:SPI:CLOCk:THReshold
BUS:B<x>:SPI:DATa:POLarity
BUS:B<x>:SPI:DATa:SIZe
BUS:B<x>:SPI:DATa:SOUrce
BUS:B<x>:SPI:DATa:THReshold
BUS:B<x>:SPI:FRAMING
BUS:B<x>:SPI:IDLETime
BUS:B<x>:SPI:MISo:DATa:POLarity
BUS:B<x>:SPI:MISo:INPut
BUS:B<x>:SPI:MISo:THReshold
BUS:B<x>:SPI:MOSi:DATa:POLarity
BUS:B<x>:SPI:MOSi:INPut
BUS:B<x>:SPI:MOSi:THReshold
BUS:B<x>:SPI:NUMBer:INputs
BUS:B<x>:SPI:SELect:POLarity
BUS:B<x>:SPI:SELect:SOUrce
BUS:B<x>:SPI:SELect:THReshold
BUS:B<x>:TYPe
BUS:DELete
BUS:LIST?
BUSTABle:ADDNew
BUSTABle:DELete
BUSTABle:LIST?
BUSY?
*CAL?
CALibrate?
CALibrate:INTERNal
CALibrate:INTERNal:STARt
CALibrate:INTERNal:STATus?
CALibrate:PWRUpstatus?
CALLOUTS:ADDNew
CALLOUTS:CALLOUT<x>:BOOKMark:SOURCE
CALLOUTS:CALLOUT<x>:BOOKMark:XPOS
CALLOUTS:CALLOUT<x>:COLOR
CALLOUTS:CALLOUT<x>:DISPLAYPOSition:X
CALLOUTS:CALLOUT<x>:DISPLAYPOSition:Y
CALLOUTS:CALLOUT<x>:FONT:BOLD
CALLOUTS:CALLOUT<x>:FONT:ITALIC
CALLOUTS:CALLOUT<x>:FONT:SIZE
CALLOUTS:CALLOUT<x>:FONT:TYPE
CALLOUTS:CALLOUT<x>:FONT:UNDERLine
CALLOUTS:CALLOUT<x>:TEXT
CALLOUTS:CALLOUT<x>:TYPE
CALLOUTS:DELete
CH<x>?
CH<x>:BANdwidth
CH<x>:CLIPping?
CH<x>:COUPling
CH<x>:DESKew
CH<x>:DITHERrange
CH<x>:INVert
CH<x>:LABel:COLor
CH<x>:LABel:FONT:BOLD
CH<x>:LABel:FONT:ITALic
CH<x>:LABel:FONT:SIZE
CH<x>:LABel:FONT:TYPE
CH<x>:LABel:FONT:UNDERline
CH<x>:LABel:NAMe
CH<x>:LABel:XPOS
CH<x>:LABel:YPOS
CH<x>:OFFSet
CH<x>:POSition
CH<x>:PROBEFunc:EXTAtten
CH<x>:PROBEFunc:EXTDBatten
CH<x>:PROBEFunc:EXTUnits
CH<x>:PROBEFunc:EXTUnits:STATE
CH<x>:SCAle
CH<x>:SCALERATio
CH<x>:TERmination
CH<x>:VTERm:BIAS
CLEAR
*CLS
CONFIGuration:ANALOg:BANDWidth?
CONNected:REQUested:STATus
CONNected:STATus?
CONNected:USAGe:TRack:REQUested:STATus
CONNected:USAGe:TRack:STATus?
CURVe?
CURVEStream?
CUSTOMTABle:ADDNew
CUSTOMTABle:DELete
CUSTOMTABle:LIST?
DATa
DATa:ENCdg
DATa:MODe
DATa:RESample
DATa:SOUrce
DATa:SOUrce:AVAILable?
DATa:STARt
DATa:STOP
DATa:WIDth
DATE?
DCH<x>_D<x>:LABel:COLor
DCH<x>_D<x>:LABel:FONT:BOLD
DCH<x>_D<x>:LABel:FONT:ITALic
DCH<x>_D<x>:LABel:FONT:SIZE
DCH<x>_D<x>:LABel:FONT:TYPE
DCH<x>_D<x>:LABel:FONT:UNDERline
DCH<x>_D<x>:LABel:NAMe
DCH<x>_D<x>:THReshold
*DDT
DESE
DIAg:LOOP:OPTion
DIAg:LOOP:OPTion:NTIMes
DIAg:LOOP:STOP
DIAg:MODe
DIAg:RESUlt?
DIAg:RESUlt:FLAg?
DIAg:RESUlt:LOG?
DIAg:SELect
DIAg:STATE
DISplay?
DISplay:{CH<x>|Math<x>|REF<x>}:INVERTColor
DISplay:{CH<x>|Math<x>|REF<x>}:NORMALColor
DISplay:COLors
DISplay:GLObal:B<x>:STATE
DISplay:GLObal:CH<x>:STATE
DISplay:GLObal:DCH<x>:STATE
DISplay:GLObal:MATH<x>:STATE
DISplay:GLObal:REF<x>:STATE
DISplay:INTENSITy?
DISplay:INTENSITy:BACKLight
DISplay:INTENSITy:BACKLight:AUTODim:ENAble
DISplay:INTENSITy:BACKLight:AUTODim:TIMe
DISplay:MATHFFTView<x>:AUTOScale
DISplay:MATHFFTView<x>:CURSor:ASOUrce?
DISplay:MATHFFTView<x>:CURSor:BSOUrce?
DISplay:MATHFFTView<x>:CURSor:DDT?
DISplay:MATHFFTView<x>:CURSor:FUNCtion
DISplay:MATHFFTView<x>:CURSor:HBArs:APOSition
DISplay:MATHFFTView<x>:CURSor:HBArs:AUNIts?
DISplay:MATHFFTView<x>:CURSor:HBArs:BPOSition
DISplay:MATHFFTView<x>:CURSor:HBArs:BUNIts?
DISplay:MATHFFTView<x>:CURSor:HBArs:DELTa?
DISplay:MATHFFTView<x>:CURSor:MODe
DISplay:MATHFFTView<x>:CURSor:ONEOVERDELTATVALUE?
DISplay:MATHFFTView<x>:CURSor:ROLOCATION
DISplay:MATHFFTView<x>:CURSor:SCREEN:AXPOSition
DISplay:MATHFFTView<x>:CURSor:SCREEN:AYPOSition
DISplay:MATHFFTView<x>:CURSor:SCREEN:BXPOSition
DISplay:MATHFFTView<x>:CURSor:SCREEN:BYPOSition
DISplay:MATHFFTView<x>:CURSor:STATE
DISplay:MATHFFTView<x>:CURSor:VBArs:APOSition
DISplay:MATHFFTView<x>:CURSor:VBArs:AUNIts?
DISplay:MATHFFTView<x>:CURSor:VBArs:BPOSition
DISplay:MATHFFTView<x>:CURSor:VBArs:BUNIts?
DISplay:MATHFFTView<x>:CURSor:VBArs:DELTa?
DISplay:MATHFFTView<x>:CURSor:WAVEform:APOSition
DISplay:MATHFFTView<x>:CURSor:WAVEform:BPOSition
DISplay:MATHFFTView<x>:GRIDlines
DISplay:MATHFFTView<x>:MATH:MATH<x>:STATE
DISplay:MATHFFTView<x>:XAXIS:SCALE
DISplay:MATHFFTView<x>:YAXIS:SCALE
DISplay:MATHFFTView<x>:ZOOM:XAXIS:FROM
DISplay:MATHFFTView<x>:ZOOM:XAXIS:TO
DISplay:MATHFFTView<x>:ZOOM:YAXIS:FROM
DISplay:MATHFFTView<x>:ZOOM:YAXIS:TO
DISplay:PERSistence
DISplay:PERSistence:RESET
DISplay:PLOTView<x>:AUTOScale
DISplay:PLOTView<x>:CURSor:ASOUrce?
DISplay:PLOTView<x>:CURSor:BSOUrce?
DISplay:PLOTView<x>:CURSor:DDT?
DISplay:PLOTView<x>:CURSor:FUNCtion
DISplay:PLOTView<x>:CURSor:HBArs:APOSition
DISplay:PLOTView<x>:CURSor:HBArs:AUNIts?
DISplay:PLOTView<x>:CURSor:HBArs:BPOSition
DISplay:PLOTView<x>:CURSor:HBArs:BUNIts?
DISplay:PLOTView<x>:CURSor:HBArs:DELTa?
DISplay:PLOTView<x>:CURSor:MODe
DISplay:PLOTView<x>:CURSor:ONEOVERDELTATVALUE?
DISplay:PLOTView<x>:CURSor:ROLOCATION
DISplay:PLOTView<x>:CURSor:SCREEN:AXPOSition
DISplay:PLOTView<x>:CURSor:SCREEN:AYPOSition
DISplay:PLOTView<x>:CURSor:SCREEN:BXPOSition
DISplay:PLOTView<x>:CURSor:SCREEN:BYPOSition
DISplay:PLOTView<x>:CURSor:SPLITMODE
DISplay:PLOTView<x>:CURSor:STATE
DISplay:PLOTView<x>:CURSor:VBArs:APOSition
DISplay:PLOTView<x>:CURSor:VBArs:BPOSition
DISplay:PLOTView<x>:CURSor:VBArs:DELTa?
DISplay:PLOTView<x>:CURSor:VBArs:UNIts?
DISplay:PLOTView<x>:CURSor:WAVEform:APOSition
DISplay:PLOTView<x>:CURSor:WAVEform:BPOSition
DISplay:PLOTView<x>:GRIDlines
DISplay:PLOTView<x>:XAXIS:SCALE
DISplay:PLOTView<x>:YAXIS:SCALE
DISplay:PLOTView<x>:ZOOM:XAXIS:FROM
DISplay:PLOTView<x>:ZOOM:XAXIS:TO
DISplay:PLOTView<x>:ZOOM:YAXIS:FROM
DISplay:PLOTView<x>:ZOOM:YAXIS:TO
DISplay:REFFFTView<x>:AUTOScale
DISplay:REFFFTView<x>:CURSor:ASOUrce?
DISplay:REFFFTView<x>:CURSor:BSOUrce?
DISplay:REFFFTView<x>:CURSor:DDT?
DISplay:REFFFTView<x>:CURSor:FUNCtion
DISplay:REFFFTView<x>:CURSor:HBArs:APOSition
DISplay:REFFFTView<x>:CURSor:HBArs:AUNIts?
DISplay:REFFFTView<x>:CURSor:HBArs:BPOSition
DISplay:REFFFTView<x>:CURSor:HBArs:BUNIts?
DISplay:REFFFTView<x>:CURSor:HBArs:DELTa?
DISplay:REFFFTView<x>:CURSor:MODe
DISplay:REFFFTView<x>:CURSor:ONEOVERDELTATVALUE?
DISplay:REFFFTView<x>:CURSor:ROLOCATION
DISplay:REFFFTView<x>:CURSor:SCREEN:AXPOSition
DISplay:REFFFTView<x>:CURSor:SCREEN:AYPOSition
DISplay:REFFFTView<x>:CURSor:SCREEN:BXPOSition
DISplay:REFFFTView<x>:CURSor:SCREEN:BYPOSition
DISplay:REFFFTView<x>:CURSor:SPLITMODE
DISplay:REFFFTView<x>:CURSor:STATE
DISplay:REFFFTView<x>:CURSor:VBArs:APOSition
DISplay:REFFFTView<x>:CURSor:VBArs:BPOSition
DISplay:REFFFTView<x>:CURSor:VBArs:DELTa?
DISplay:REFFFTView<x>:CURSor:VBArs:UNIts?
DISplay:REFFFTView<x>:CURSor:WAVEform:AHPOSition?
DISplay:REFFFTView<x>:CURSor:WAVEform:APOSition
DISplay:REFFFTView<x>:CURSor:WAVEform:AVPOSition?
DISplay:REFFFTView<x>:CURSor:WAVEform:BHPOSition?
DISplay:REFFFTView<x>:CURSor:WAVEform:BPOSition
DISplay:REFFFTView<x>:CURSor:WAVEform:BVPOSition?
DISplay:REFFFTView<x>:GRIDlines
DISplay:REFFFTView<x>:REF:REF<x>:STATE
DISplay:REFFFTView<x>:XAXIS:SCALE
DISplay:REFFFTView<x>:ZOOM:XAXIS:FROM
DISplay:REFFFTView<x>:ZOOM:XAXIS:TO
DISplay:REFFFTView<x>:ZOOM:YAXIS:FROM
DISplay:REFFFTView<x>:ZOOM:YAXIS:TO
DISplay:SELect:BUS
DISplay:SELect:MATH
DISplay:SELect:REFerence
DISplay:SELect:SOUrce
DISplay:SELect:VIEW
DISplay:SELect:WAVEView<x>:SOUrce
DISplay:VARpersist
DISplay:WAVEform
DISplay:WAVEView:CURSor:CURSOR1:ROLOCATION
DISplay:WAVEView:GRIDTYPE
DISplay:WAVEView<x>:BUS:B<x>:STATE
DISplay:WAVEView<x>:BUS:B<x>:VERTical:POSition
DISplay:WAVEView<x>:CH<x>:STATE
DISplay:WAVEView<x>:CH<x>:VERTical:POSition
DISplay:WAVEView<x>:CH<x>:VERTical:SCAle
DISplay:WAVEView<x>:CURSor?
DISplay:WAVEView<x>:CURSor:CURSOR:WAVEform:AVPOSition?
DISplay:WAVEView<x>:CURSor:CURSOR:WAVEform:BVPOSition?
DISplay:WAVEView<x>:CURSor:CURSOR<x>?
DISplay:WAVEView<x>:CURSor:CURSOR<x>:ASOUrce
DISplay:WAVEView<x>:CURSor:CURSOR<x>:BSOUrce
DISplay:WAVEView<x>:CURSor:CURSOR<x>:DDT?
DISplay:WAVEView<x>:CURSor:CURSOR<x>:FUNCtion
DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:APOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:AUNIts?
DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:BPOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:BUNIts?
DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:DELTa?
DISplay:WAVEView<x>:CURSor:CURSOR<x>:MODe
DISplay:WAVEView<x>:CURSor:CURSOR<x>:ONEOVERDELTATVALUE?
DISplay:WAVEView<x>:CURSor:CURSOR<x>:SCREEN:AXPOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:SCREEN:AYPOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:SCREEN:BXPOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:SCREEN:BYPOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:SPLITMODE
DISplay:WAVEView<x>:CURSor:CURSOR<x>:STATE
DISplay:WAVEView<x>:CURSor:CURSOR<x>:VBArs:APOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:VBArs:BPOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:VBArs:DELTa?
DISplay:WAVEView<x>:CURSor:CURSOR<x>:VBArs:UNIts?
DISplay:WAVEView<x>:CURSor:CURSOR<x>:WAVEform:APOSition
DISplay:WAVEView<x>:CURSor:CURSOR<x>:WAVEform:BPOSition
DISplay:WAVEView<x>:DCH<x>_D<x>:STATE
DISplay:WAVEView<x>:DCH<x>_DALL:DIGORDER
DISplay:WAVEView<x>:DCH<x>_DALL:VERTical:POSition
DISplay:WAVEView<x>:FILTer
DISplay:WAVEView<x>:GRAticule
DISplay:WAVEView<x>:INTENSITy:GRATicule
DISplay:WAVEView<x>:INTENSITy:WAVEform
DISplay:WAVEView<x>:MATH:MATH<x>:AUTOScale
DISplay:WAVEView<x>:MATH:MATH<x>:STATE
DISplay:WAVEView<x>:MATH:MATH<x>:VERTical:POSition
DISplay:WAVEView<x>:MATH:MATH<x>:VERTical:SCAle
DISplay:WAVEView<x>:REF:REF<x>:STATE
DISplay:WAVEView<x>:REF:REF<x>:VERTical:POSition
DISplay:WAVEView<x>:REF:REF<x>:VERTical:SCAle
DISplay:WAVEView<x>:STYle
DISplay:WAVEView<x>:VIEWStyle
DISplay:WAVEView<x>:ZOOM?
DISplay:WAVEView<x>:ZOOM:ZOOM<x>?
DISplay:WAVEView<x>:ZOOM:ZOOM<x>:HORizontal:POSition
DISplay:WAVEView<x>:ZOOM:ZOOM<x>:HORizontal:SCALe
DISplay:WAVEView<x>:ZOOM:ZOOM<x>:HORizontal:WINSCALe
DISplay:WAVEView<x>:ZOOM:ZOOM<x>:STATe
DISplay:WAVEView<x>:ZOOM:ZOOM<x>:VERTical:POSition
DISplay:WAVEView<x>:ZOOM:ZOOM<x>:VERTical:SCALe
DISplay:WAVEView<y>:REF:REF<x>:FRAMe
DISplay:WAVEView<y>:REF<x>_DALL:FRAMe
*ESE
*ESR?
ETHERnet:DHCPbootp
ETHERnet:DNS:IPADDress
ETHERnet:DOMAINname
ETHERnet:ENET:ADDress?
ETHERnet:GATEWay:IPADDress
ETHERnet:IPADDress
ETHERnet:LXI:LAN:RESET
ETHERnet:LXI:LAN:SERVICENAMe
ETHERnet:LXI:LAN:STATus?
ETHERnet:NAME
ETHERnet:NETWORKCONFig
ETHERnet:PING
ETHERnet:PING:STATus?
ETHERnet:SUBNETMask
EVENT?
EVMsg?
EVQty?
FACtory
FILESystem?
FILESystem:COPy
FILESystem:CWD
FILESystem:DELEte
FILESystem:DIR?
FILESystem:HOMEDir?
FILESystem:LDIR?
FILESystem:MKDir
FILESystem:MOUNT:DRIVE
FILESystem:MOUNT:TEKDrive
FILESystem:READFile
FILESystem:REName
FILESystem:RMDir
FILESystem:TEKDrive:CODE?
FILESystem:TEKDrive:CODE:EXPirytime?
FILESystem:TEKDrive:CODE:STATus?
FILESystem:UNMOUNT:DRIve
FILESystem:UNMOUNT:TEKDrive
FILESystem:WRITEFile
FPAnel:PRESS
FPAnel:TURN
HEADer
HORizontal?
HORizontal:ACQDURATION?
HORizontal:DELay:MODe
HORizontal:DELay:TIMe
HORizontal:DIVisions?
HORizontal:MAIn:INTERPRatio?
HORizontal:MODE
HORizontal:MODE:MANual:CONFIGure
HORizontal:MODE:RECOrdlength
HORizontal:MODE:SAMPLERate
HORizontal:MODE:SCAle
HORizontal:POSition
HORizontal:PREViewstate?
HORizontal:RECOrdlength
HORizontal:SAMPLERate
HORizontal:SAMPLERate:ANALYZemode:MINimum:OVERRide
HORizontal:SAMPLERate:ANALYZemode:MINimum:VALue
HORizontal:SCAle
ID?
*IDN?
LIC:UNINSTALL?
LICense?
LICense:APPID?
LICense:COUNt?
LICense:ERRor?
LICense:GMT?
LICense:HID?
LICense:INSTall
LICense:ITEM?
LICense:LIST?
LICense:VALidate?
LOCk
*LRN?
MAINWindow:BADGe:BRINgtoview
MAINWindow:FONTSize
MAINWindow:RRBDisplaystate
MASK:DELete
MASK:MASK<x>:COUNT?
MASK:MASK<x>:COUNT:HITS?
MASK:MASK<x>:COUNT:SEG<x>:HITS?
MASK:MASK<x>:DEFinedby
MASK:MASK<x>:DISplay
MASK:MASK<x>:LIST?
MASK:MASK<x>:SEG<x>:POINTS
MASK:MASK<x>:SOUrce
MASK:MASK<x>:TESt:STATE
MASK:MASK<x>:TESt:STATUS?
MASK:MASK<x>:TESt:THReshold
MASK:MASK<x>:TOLerance:HORizontal
MASK:MASK<x>:TOLerance:UPDatenow
MASK:MASK<x>:TOLerance:VERTical
MASK:TESt:WAVEforms
MATH:ADDNew
MATH:DELete
MATH:LIST?
MATH:MATH<x>:AVG:MODE
MATH:MATH<x>:AVG:WEIGht
MATH:MATH<x>:CAN:SUPPortedfields
MATH:MATH<x>:DEFine
MATH:MATH<x>:FUNCtion
MATH:MATH<x>:GATing
MATH:MATH<x>:I2C:SUPPortedfields
MATH:MATH<x>:INTERpolation
MATH:MATH<x>:LABel:COLor
MATH:MATH<x>:LABel:FONT:BOLD
MATH:MATH<x>:LABel:FONT:ITALic
MATH:MATH<x>:LABel:FONT:SIZE
MATH:MATH<x>:LABel:FONT:TYPE
MATH:MATH<x>:LABel:FONT:UNDERline
MATH:MATH<x>:LABel:NAMe
MATH:MATH<x>:LABel:XPOS
MATH:MATH<x>:LABel:YPOS
MATH:MATH<x>:LIN:SUPPortedfields
MATH:MATH<x>:PARallel:SUPPortedfields
MATH:MATH<x>:RS232C:SUPPortedfields
MATH:MATH<x>:SENT:SUPPortedfields
MATH:MATH<x>:SIGNeddata
MATH:MATH<x>:SOUrce<x>
MATH:MATH<x>:SPECTral:WINdow
MATH:MATH<x>:SPI:SUPPortedfields
MATH:MATH<x>:TYPe
MATH:MATH<x>:VUNIT
MEASTABle:ADDNew
MEASTABle:DELETE
MEASUrement?
MEASUrement:ADDMEAS
MEASUrement:ADDNew
MEASUrement:ANNOTate
MEASUrement:CH<x>:REFLevels:ABSolute:FALLHigh
MEASUrement:CH<x>:REFLevels:ABSolute:FALLLow
MEASUrement:CH<x>:REFLevels:ABSolute:FALLMid
MEASUrement:CH<x>:REFLevels:ABSolute:HYSTeresis
MEASUrement:CH<x>:REFLevels:ABSolute:RISEHigh
MEASUrement:CH<x>:REFLevels:ABSolute:RISELow
MEASUrement:CH<x>:REFLevels:ABSolute:RISEMid
MEASUrement:CH<x>:REFLevels:ABSolute:TYPE
MEASUrement:CH<x>:REFLevels:BASETop
MEASUrement:CH<x>:REFLevels:METHod
MEASUrement:CH<x>:REFLevels:PERCent:FALLHigh
MEASUrement:CH<x>:REFLevels:PERCent:FALLLow
MEASUrement:CH<x>:REFLevels:PERCent:FALLMid
MEASUrement:CH<x>:REFLevels:PERCent:HYSTeresis
MEASUrement:CH<x>:REFLevels:PERCent:RISEHigh
MEASUrement:CH<x>:REFLevels:PERCent:RISELow
MEASUrement:CH<x>:REFLevels:PERCent:RISEMid
MEASUrement:CH<x>:REFLevels:PERCent:TYPE
MEASUrement:DELete
MEASUrement:DELETEALL
MEASUrement:EDGE<x>
MEASUrement:GATing
MEASUrement:GATing:ACTive
MEASUrement:GATing:ENDtime
MEASUrement:GATing:HYSTeresis
MEASUrement:GATing:LOGICSource
MEASUrement:GATing:MIDRef
MEASUrement:GATing:SEARCHSource
MEASUrement:GATing:STARTtime
MEASUrement:INTERp
MEASUrement:LIST?
MEASUrement:MATH<x>:REFLevels:ABSolute:FALLHigh
MEASUrement:MATH<x>:REFLevels:ABSolute:FALLLow
MEASUrement:MATH<x>:REFLevels:ABSolute:FALLMid
MEASUrement:MATH<x>:REFLevels:ABSolute:HYSTeresis
MEASUrement:MATH<x>:REFLevels:ABSolute:RISEHigh
MEASUrement:MATH<x>:REFLevels:ABSolute:RISELow
MEASUrement:MATH<x>:REFLevels:ABSolute:RISEMid
MEASUrement:MATH<x>:REFLevels:ABSolute:TYPE
MEASUrement:MATH<x>:REFLevels:BASETop
MEASUrement:MATH<x>:REFLevels:METHod
MEASUrement:MATH<x>:REFLevels:PERCent:FALLHigh
MEASUrement:MATH<x>:REFLevels:PERCent:FALLLow
MEASUrement:MATH<x>:REFLevels:PERCent:FALLMid
MEASUrement:MATH<x>:REFLevels:PERCent:HYSTeresis
MEASUrement:MATH<x>:REFLevels:PERCent:RISEHigh
MEASUrement:MATH<x>:REFLevels:PERCent:RISELow
MEASUrement:MATH<x>:REFLevels:PERCent:RISEMid
MEASUrement:MATH<x>:REFLevels:PERCent:TYPE
MEASUrement:MEAS<x>:BURSTEDGTYPe
MEASUrement:MEAS<x>:CCRESUlts:ALLAcqs:MAXimum?
MEASUrement:MEAS<x>:CCRESUlts:ALLAcqs:MEAN?
MEASUrement:MEAS<x>:CCRESUlts:ALLAcqs:MINimum?
MEASUrement:MEAS<x>:CCRESUlts:ALLAcqs:PK2PK?
MEASUrement:MEAS<x>:CCRESUlts:ALLAcqs:POPUlation?
MEASUrement:MEAS<x>:CCRESUlts:ALLAcqs:STDDev?
MEASUrement:MEAS<x>:CCRESUlts:CURRentacq:MAXimum?
MEASUrement:MEAS<x>:CCRESUlts:CURRentacq:MEAN?
MEASUrement:MEAS<x>:CCRESUlts:CURRentacq:MINimum?
MEASUrement:MEAS<x>:CCRESUlts:CURRentacq:PK2PK?
MEASUrement:MEAS<x>:CCRESUlts:CURRentacq:POPUlation?
MEASUrement:MEAS<x>:CCRESUlts:CURRentacq:STDDev?
MEASUrement:MEAS<x>:DELay:EDGE<x>
MEASUrement:MEAS<x>:DISPlaystat:ENABle
MEASUrement:MEAS<x>:EDGE<x>
MEASUrement:MEAS<x>:EDGEIncre
MEASUrement:MEAS<x>:EDGES:FROMLevel
MEASUrement:MEAS<x>:EDGES:LEVel
MEASUrement:MEAS<x>:EDGES:N
MEASUrement:MEAS<x>:EDGES:SLEWRATEMethod
MEASUrement:MEAS<x>:EDGES:TOLevel
MEASUrement:MEAS<x>:FAILCount?
MEASUrement:MEAS<x>:FROMedge
MEASUrement:MEAS<x>:FROMEDGESEARCHDIRect
MEASUrement:MEAS<x>:GATing
MEASUrement:MEAS<x>:GATing:ACTive
MEASUrement:MEAS<x>:GATing:ENDtime
MEASUrement:MEAS<x>:GATing:GLOBal
MEASUrement:MEAS<x>:GATing:HYSTeresis
MEASUrement:MEAS<x>:GATing:LOGICSource
MEASUrement:MEAS<x>:GATing:MIDRef
MEASUrement:MEAS<x>:GATing:SEARCHSource
MEASUrement:MEAS<x>:GATing:STARTtime
MEASUrement:MEAS<x>:GLOBalref
MEASUrement:MEAS<x>:HIGHREFVoltage
MEASUrement:MEAS<x>:IDLETime
MEASUrement:MEAS<x>:LABel
MEASUrement:MEAS<x>:LOWREFVoltage
MEASUrement:MEAS<x>:PASSFAILENabled
MEASUrement:MEAS<x>:PASSFAILHIGHlimit
MEASUrement:MEAS<x>:PASSFAILLIMit
MEASUrement:MEAS<x>:PASSFAILLOWlimit
MEASUrement:MEAS<x>:PASSFAILMARgin
MEASUrement:MEAS<x>:PASSFAILWHEN
MEASUrement:MEAS<x>:PERFREQ:EDGE
MEASUrement:MEAS<x>:POLarity
MEASUrement:MEAS<x>:REFLevels:ABSolute:FALLHigh
MEASUrement:MEAS<x>:REFLevels<x>:ABSolute:FALLLow
MEASUrement:MEAS<x>:REFLevels<x>:ABSolute:FALLMid
MEASUrement:MEAS<x>:REFLevels<x>:ABSolute:HYSTeresis
MEASUrement:MEAS<x>:REFLevels<x>:ABSolute:RISEHigh
MEASUrement:MEAS<x>:REFLevels<x>:ABSolute:RISELow
MEASUrement:MEAS<x>:REFLevels<x>:ABSolute:RISEMid
MEASUrement:MEAS<x>:REFLevels<x>:ABSolute:TYPE
MEASUrement:MEAS<x>:REFLevels<x>:BASETop
MEASUrement:MEAS<x>:REFLevels<x>:METHod
MEASUrement:MEAS<x>:REFLevels<x>:PERCent:FALLHigh
MEASUrement:MEAS<x>:REFLevels<x>:PERCent:FALLLow
MEASUrement:MEAS<x>:REFLevels<x>:PERCent:FALLMid
MEASUrement:MEAS<x>:REFLevels<x>:PERCent:HYSTeresis
MEASUrement:MEAS<x>:REFLevels<x>:PERCent:RISEHigh
MEASUrement:MEAS<x>:REFLevels<x>:PERCent:RISELow
MEASUrement:MEAS<x>:REFLevels<x>:PERCent:RISEMid
MEASUrement:MEAS<x>:REFLevels<x>:PERCent:TYPE
MEASUrement:MEAS<x>:REFMode
MEASUrement:MEAS<x>:REFVoltage
MEASUrement:MEAS<x>:RESUlts:ALLAcqs:MAXimum?
MEASUrement:MEAS<x>:RESUlts:ALLAcqs:MEAN?
MEASUrement:MEAS<x>:RESUlts:ALLAcqs:MINimum?
MEASUrement:MEAS<x>:RESUlts:ALLAcqs:PK2PK?
MEASUrement:MEAS<x>:RESUlts:ALLAcqs:POPUlation?
MEASUrement:MEAS<x>:RESUlts:ALLAcqs:STDDev?
MEASUrement:MEAS<x>:RESUlts:CURRentacq:MAXimum?
MEASUrement:MEAS<x>:RESUlts:CURRentacq:MEAN?
MEASUrement:MEAS<x>:RESUlts:CURRentacq:MINimum?
MEASUrement:MEAS<x>:RESUlts:CURRentacq:PK2PK?
MEASUrement:MEAS<x>:RESUlts:CURRentacq:POPUlation?
MEASUrement:MEAS<x>:RESUlts:CURRentacq:STDDev?
MEASUrement:MEAS<x>:SIGNALType
MEASUrement:MEAS<x>:SOUrce<x>
MEASUrement:MEAS<x>:STATUS?
MEASUrement:MEAS<x>:TOEdge
MEASUrement:MEAS<x>:TOEDGESEARCHDIRect
MEASUrement:MEAS<x>:TRANSition
MEASUrement:MEAS<x>:TYPe
MEASUrement:MEAS<x>:XUNIT?
MEASUrement:MEAS<x>:YUNIT?
MEASUrement:REF<x>:REFLevels:ABSolute:FALLHigh
MEASUrement:REF<x>:REFLevels:ABSolute:FALLLow
MEASUrement:REF<x>:REFLevels:ABSolute:FALLMid
MEASUrement:REF<x>:REFLevels:ABSolute:HYSTeresis
MEASUrement:REF<x>:REFLevels:ABSolute:RISEHigh
MEASUrement:REF<x>:REFLevels:ABSolute:RISELow
MEASUrement:REF<x>:REFLevels:ABSolute:RISEMid
MEASUrement:REF<x>:REFLevels:ABSolute:TYPE
MEASUrement:REF<x>:REFLevels:BASETop
MEASUrement:REF<x>:REFLevels:METHod
MEASUrement:REF<x>:REFLevels:PERCent:FALLHigh
MEASUrement:REF<x>:REFLevels:PERCent:FALLLow
MEASUrement:REF<x>:REFLevels:PERCent:FALLMid
MEASUrement:REF<x>:REFLevels:PERCent:HYSTeresis
MEASUrement:REF<x>:REFLevels:PERCent:RISEHigh
MEASUrement:REF<x>:REFLevels:PERCent:RISELow
MEASUrement:REF<x>:REFLevels:PERCent:RISEMid
MEASUrement:REF<x>:REFLevels:PERCent:TYPE
MEASUrement:REFLevels:ABSolute:FALLHigh
MEASUrement:REFLevels:ABSolute:FALLLow
MEASUrement:REFLevels:ABSolute:FALLMid
MEASUrement:REFLevels:ABSolute:HYSTeresis
MEASUrement:REFLevels:ABSolute:RISEHigh
MEASUrement:REFLevels:ABSolute:RISELow
MEASUrement:REFLevels:ABSolute:RISEMid
MEASUrement:REFLevels:ABSolute:TYPE
MEASUrement:REFLevels:BASETop
MEASUrement:REFLevels:METHod
MEASUrement:REFLevels:MODE
MEASUrement:REFLevels:PERCent:FALLHigh
MEASUrement:REFLevels:PERCent:FALLLow
MEASUrement:REFLevels:PERCent:FALLMid
MEASUrement:REFLevels:PERCent:HYSTeresis
MEASUrement:REFLevels:PERCent:RISEHigh
MEASUrement:REFLevels:PERCent:RISELow
MEASUrement:REFLevels:PERCent:RISEMid
MEASUrement:REFLevels:PERCent:TYPE
MEASUrement:REFLevels:TYPE
MEASUrement:STATIstics:CYCLEMode
NEWpass
*OPC
*OPT?
PASSWord
PAUSe
PG:AMPlitude
PG:BIT:ONE
PG:BIT:THREE
PG:BIT:TWO
PG:BIT:ZERO
PG:BITRate
PG:BURSt:CCOUnt
PG:BURSt:TRIGger
PG:FILE:PATTern
PG:OUTPut:MODe
PG:PATTERNdefinition
PLOT:ADDNew
PLOT:DELete
PLOT:LIST?
PLOT:PLOT<x>:SOUrce<x>
PLOT:PLOT<x>:TYPe
POWer:ADDNew
POWer:DELete
POWer:POWer<x>:CLRESPONSE:AMP<x>Val
POWer:POWer<x>:CLRESPONSE:AMPMode
POWer:POWer<x>:CLRESPONSE:ANALYSISMethod?
POWer:POWer<x>:CLRESPONSE:CONNECTSTATus?
POWer:POWer<x>:CLRESPONSE:CONSTAMPlitude
POWer:POWer<x>:CLRESPONSE:FREQ<x>Val
POWer:POWer<x>:CLRESPONSE:GENerator
POWer:POWer<x>:CLRESPONSE:GENIPADDress
POWer:POWer<x>:CLRESPONSE:IMPEDance
POWer:POWer<x>:CLRESPONSE:INPUTSOurce
POWer:POWer<x>:CLRESPONSE:OUTPUTSOurce
POWer:POWer<x>:CLRESPONSE:PPD
POWer:POWer<x>:CLRESPONSE:STARTFREQuency
POWer:POWer<x>:CLRESPONSE:STOPFREQuency
POWer:POWer<x>:CLRESPONSE:TESTCONNection
POWer:POWer<x>:PRESET
POWer:POWer<x>:RESUlts:CURRentacq:MAXimum?
POWer:POWer<x>:RESUlts:CURRentacq:MEAN?
POWer:POWer<x>:RESUlts:CURRentacq:MINimum?
*PSC
*PUD
RECAll:MASK
RECAll:SESsion
RECAll:SETUp
RECAll:WAVEform
REF:ADDNew
REF:DELete
REF:LIST?
REF:REF<x>:DESKew
REF:REF<x>:LABel:COLor
REF:REF<x>:LABel:FONT:BOLD
REF:REF<x>:LABel:FONT:ITALic
REF:REF<x>:LABel:FONT:SIZE
REF:REF<x>:LABel:FONT:TYPE
REF:REF<x>:LABel:FONT:UNDERline
REF:REF<x>:LABel:NAMe
REF:REF<x>:LABel:XPOS
REF:REF<x>:LABel:YPOS
REF:REF<x>:SOUrce
REM
ROSc:SOUrce
ROSc:STATE?
*RST
SAVe:EVENTtable:BUS
SAVe:EVENTtable:MEASUrement
SAVe:EVENTtable:SEARCHTable
SAVe:IMAGe
SAVe:IMAGe:COMPosition
SAVe:IMAGe:VIEWTYpe
SAVe:PLOTData
SAVe:REPOrt
SAVe:REPOrt:COMMents
SAVe:SESsion
SAVe:SETUp
SAVe:SETUp:INCLUDEREFs
SAVe:WAVEform
SAVe:WAVEform:GATing
SAVe:WAVEform:GATing:RESAMPLErate
SAVe:WAVEform:SOURCELIst?
SAVEON:FILE:DEST
SAVEON:FILE:NAME
SAVEON:IMAGe
SAVEON:IMAGe:FILEFormat
SAVEON:TRIGger
SAVEON:WAVEform
SAVEON:WAVEform:FILEFormat
SAVEON:WAVEform:SOURce
SAVEONEVent:FILEDest
SAVEONEVent:FILEName
SAVEONEVent:IMAGe:FILEFormat
SAVEONEVent:WAVEform:FILEFormat
SAVEONEVent:WAVEform:SOUrce
SCOPEApp REBOOT
SEARCH:ADDNew
SEARCH:DELete
SEARCH:DELETEALL
SEARCH:LIST?
SEARCH:SEARCH<x>:COPy
SEARCH:SEARCH<x>:NAVigate
SEARCH:SEARCH<x>:TOTAL?
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:CONDition
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:DATa:DIRection
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:DATa:OFFSet
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:DATa:QUALifier
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:DATa:SIZe
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:DATa:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:ERRType
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:FD:BRSBit
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:FD:ESIBit
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:FRAMEtype
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:IDentifier:MODe
SEARCH:SEARCH<x>:TRIGger:A:BUS:CAN:IDentifier:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:I2C:ADDRess:MODe
SEARCH:SEARCH<x>:TRIGger:A:BUS:I2C:ADDRess:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:I2C:CONDition
SEARCH:SEARCH<x>:TRIGger:A:BUS:I2C:DATa:DIRection
SEARCH:SEARCH<x>:TRIGger:A:BUS:I2C:DATa:SIZe
SEARCH:SEARCH<x>:TRIGger:A:BUS:I2C:DATa:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:LIN:CONDition
SEARCH:SEARCH<x>:TRIGger:A:BUS:LIN:DATa:HIVALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:LIN:DATa:QUALifier
SEARCH:SEARCH<x>:TRIGger:A:BUS:LIN:DATa:SIZe
SEARCH:SEARCH<x>:TRIGger:A:BUS:LIN:DATa:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:LIN:ERRTYPE
SEARCH:SEARCH<x>:TRIGger:A:BUS:LIN:IDentifier:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:PARallel:DATa:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:RS232C:CONDition
SEARCH:SEARCH<x>:TRIGger:A:BUS:RS232C:DATa:SIZe
SEARCH:SEARCH<x>:TRIGger:A:BUS:RS232C:DATa:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:CONDition
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:ERRType
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:ERRType:CRC
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:CHAN1A:HIVALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:CHAN1A:QUALifier
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:CHAN1A:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:CHAN2B:HIVALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:CHAN2B:QUALifier
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:CHAN2B:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:COUNTer:HIVALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:COUNTer:QUALifier
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:COUNTer:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:INVERTNIBble:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:FAST:STATus:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:PAUSE:QUALifier
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:PAUSE:TICKs:HIVALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:PAUSE:TICKs:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:SLOW:DATA:HIVALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:SLOW:DATA:QUALifier
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:SLOW:DATA:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SENT:SLOW:IDentifier:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SOUrce
SEARCH:SEARCH<x>:TRIGger:A:BUS:SPI:CONDition
SEARCH:SEARCH<x>:TRIGger:A:BUS:SPI:DATa:SIZe
SEARCH:SEARCH<x>:TRIGger:A:BUS:SPI:DATa:VALue
SEARCH:SEARCH<x>:TRIGger:A:BUS:SPI:SOURCETYpe
SEARCH:SEARCH<x>:TRIGger:A:EDGE:SLOpe
SEARCH:SEARCH<x>:TRIGger:A:EDGE:SOUrce
SEARCH:SEARCH<x>:TRIGger:A:EDGE:THReshold
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:CLOCk:THReshold
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:DELTatime
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:FUNCtion
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:INPUT:CLOCK:SOUrce
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:LEVel:CH<x>
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:LEVel:MATH<x>
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:LEVel:REF<x>
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:LOGICPattern:CH<x>
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:LOGICPattern:DCH<x>_D<x>
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:LOGICPattern:MATH<x>
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:LOGICPattern:REF<x>
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:POLarity
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:USEClockedge
SEARCH:SEARCH<x>:TRIGger:A:LOGIc:WHEn
SEARCH:SEARCH<x>:TRIGger:A:PULSEWidth:HIGHLimit
SEARCH:SEARCH<x>:TRIGger:A:PULSEWidth:LOGICQUALification
SEARCH:SEARCH<x>:TRIGger:A:PULSEWidth:LOWLimit
SEARCH:SEARCH<x>:TRIGger:A:PULSEWidth:POLarity
SEARCH:SEARCH<x>:TRIGger:A:PULSEWidth:SOUrce
SEARCH:SEARCH<x>:TRIGger:A:PULSEWidth:THReshold
SEARCH:SEARCH<x>:TRIGger:A:PULSEWidth:WHEn
SEARCH:SEARCH<x>:TRIGger:A:RUNT:LOGICQUALification
SEARCH:SEARCH<x>:TRIGger:A:RUNT:POLarity
SEARCH:SEARCH<x>:TRIGger:A:RUNT:SOUrce
SEARCH:SEARCH<x>:TRIGger:A:RUNT:THReshold:HIGH
SEARCH:SEARCH<x>:TRIGger:A:RUNT:THReshold:LOW
SEARCH:SEARCH<x>:TRIGger:A:RUNT:WHEn
SEARCH:SEARCH<x>:TRIGger:A:RUNT:WIDth
SEARCH:SEARCH<x>:TRIGger:A:SETHold:CLOCk:EDGE
SEARCH:SEARCH<x>:TRIGger:A:SETHold:CLOCk:SOUrce
SEARCH:SEARCH<x>:TRIGger:A:SETHold:CLOCk:THReshold
SEARCH:SEARCH<x>:TRIGger:A:SETHold:HOLDTime
SEARCH:SEARCH<x>:TRIGger:A:SETHold:LEVel:CH<x>
SEARCH:SEARCH<x>:TRIGger:A:SETHold:LEVel:MATH<x>
SEARCH:SEARCH<x>:TRIGger:A:SETHold:LEVel:REF<x>
SEARCH:SEARCH<x>:TRIGger:A:SETHold:LOGICPattern:CH<x>
SEARCH:SEARCH<x>:TRIGger:A:SETHold:LOGICPattern:DCH<x>_D<x>
SEARCH:SEARCH<x>:TRIGger:A:SETHold:LOGICPattern:MATH<x>
SEARCH:SEARCH<x>:TRIGger:A:SETHold:LOGICPattern:REF<x>
SEARCH:SEARCH<x>:TRIGger:A:SETHold:SETTime
SEARCH:SEARCH<x>:TRIGger:A:STATE
SEARCH:SEARCH<x>:TRIGger:A:STOPAcq
SEARCH:SEARCH<x>:TRIGger:A:TIMEOut:LOGICQUALification
SEARCH:SEARCH<x>:TRIGger:A:TIMEOut:POLarity
SEARCH:SEARCH<x>:TRIGger:A:TIMEOut:SOUrce
SEARCH:SEARCH<x>:TRIGger:A:TIMEOut:THReshold
SEARCH:SEARCH<x>:TRIGger:A:TIMEOut:TIMe
SEARCH:SEARCH<x>:TRIGger:A:TYPe
SEARCH:SELected
SECurity:LOGger:STATe
SELect:CH<x>
SELect:DCH<x>:DAll
SET?
SOCKETServer:ENAble
SOCKETServer:PORT
SOCKETServer:PROTOCol
*SRE
*STB?
TEKSecure
TIMe
TIMe:ZONe
TIMe:ZONe:UTCDELTa
TOTaluptime?
TOUCHSCReen:STATe
*TRG
TRIGger
TRIGger:A
TRIGger:A:BUS:B<x>:CAN:CONDition
TRIGger:A:BUS:B<x>:CAN:DATa:DIRection
TRIGger:A:BUS:B<x>:CAN:DATa:OFFSet
TRIGger:A:BUS:B<x>:CAN:DATa:QUALifier
TRIGger:A:BUS:B<x>:CAN:DATa:SIZe
TRIGger:A:BUS:B<x>:CAN:DATa:VALue
TRIGger:A:BUS:B<x>:CAN:ERRType
TRIGger:A:BUS:B<x>:CAN:FD:BRSBit
TRIGger:A:BUS:B<x>:CAN:FD:ESIBit
TRIGger:A:BUS:B<x>:CAN:FRAMEtype
TRIGger:A:BUS:B<x>:CAN:IDentifier:MODe
TRIGger:A:BUS:B<x>:CAN:IDentifier:VALue
TRIGger:A:BUS:B<x>:I2C:ADDRess:MODe
TRIGger:A:BUS:B<x>:I2C:ADDRess:VALue
TRIGger:A:BUS:B<x>:I2C:CONDition
TRIGger:A:BUS:B<x>:I2C:DATa:DIRection
TRIGger:A:BUS:B<x>:I2C:DATa:SIZe
TRIGger:A:BUS:B<x>:I2C:DATa:VALue
TRIGger:A:BUS:B<x>:LIN:CONDition
TRIGger:A:BUS:B<x>:LIN:DATa:HIVALue
TRIGger:A:BUS:B<x>:LIN:DATa:QUALifier
TRIGger:A:BUS:B<x>:LIN:DATa:SIZe
TRIGger:A:BUS:B<x>:LIN:DATa:VALue
TRIGger:A:BUS:B<x>:LIN:ERRTYPE
TRIGger:A:BUS:B<x>:LIN:IDentifier:VALue
TRIGger:A:BUS:B<x>:PARallel:DATa:VALue
TRIGger:A:BUS:B<x>:RS232C:CONDition
TRIGger:A:BUS:B<x>:RS232C:DATa:SIZe
TRIGger:A:BUS:B<x>:RS232C:DATa:VALue
TRIGger:A:BUS:B<x>:SENT:CONDition
TRIGger:A:BUS:B<x>:SENT:ERRType
TRIGger:A:BUS:B<x>:SENT:ERRType:CRC
TRIGger:A:BUS:B<x>:SENT:FAST:CHAN1A:HIVALue
TRIGger:A:BUS:B<x>:SENT:FAST:CHAN1A:QUALifier
TRIGger:A:BUS:B<x>:SENT:FAST:CHAN1A:VALue
TRIGger:A:BUS:B<x>:SENT:FAST:CHAN2B:HIVALue
TRIGger:A:BUS:B<x>:SENT:FAST:CHAN2B:QUALifier
TRIGger:A:BUS:B<x>:SENT:FAST:CHAN2B:VALue
TRIGger:A:BUS:B<x>:SENT:FAST:COUNTer:HIVALue
TRIGger:A:BUS:B<x>:SENT:FAST:COUNTer:QUALifier
TRIGger:A:BUS:B<x>:SENT:FAST:COUNTer:VALue
TRIGger:A:BUS:B<x>:SENT:FAST:INVERTNIBble:VALue
TRIGger:A:BUS:B<x>:SENT:FAST:STATus:VALue
TRIGger:A:BUS:B<x>:SENT:PAUSE:QUALifier
TRIGger:A:BUS:B<x>:SENT:SLOW:DATA:HIVALue
TRIGger:A:BUS:B<x>:SENT:SLOW:DATA:QUALifier
TRIGger:A:BUS:B<x>:SENT:SLOW:DATA:VALue
TRIGger:A:BUS:B<x>:SENT:SLOW:IDentifier:VALue
TRIGger:A:BUS:B<x>:SPI:CONDition
TRIGger:A:BUS:B<x>:SPI:DATa:SIZe
TRIGger:A:BUS:B<x>:SPI:DATa:VALue
TRIGger:A:BUS:SOUrce
TRIGger:A:EDGE:COUPling
TRIGger:A:EDGE:SLOpe
TRIGger:A:EDGE:SOUrce
TRIGger:A:HOLDoff:TIMe
TRIGger:A:LEVel:CH<x>
TRIGger:A:LOGIc:DELTatime
TRIGger:A:LOGIc:FUNCtion
TRIGger:A:LOGIc:INPut:CLOCk:SOUrce
TRIGger:A:LOGIc:POLarity
TRIGger:A:LOGIc:USECLockedge
TRIGger:A:LOGIc:WHEn
TRIGger:A:LOGICPattern:CH<x>
TRIGger:A:LOGICPattern:DCH<x>_D<x>
TRIGger:A:LOWerthreshold:CH<x>
TRIGger:A:MODe
TRIGger:A:PULSEWidth:HIGHLimit
TRIGger:A:PULSEWidth:LOWLimit
TRIGger:A:PULSEWidth:POLarity
TRIGger:A:PULSEWidth:SOUrce
TRIGger:A:PULSEWidth:WHEn
TRIGger:A:RUNT:POLarity
TRIGger:A:RUNT:SOUrce
TRIGger:A:RUNT:WHEn
TRIGger:A:RUNT:WIDth
TRIGger:A:SETHold:CLOCk:EDGE
TRIGger:A:SETHold:CLOCk:SOUrce
TRIGger:A:SETHold:HOLDTime
TRIGger:A:SETHold:SETTime
TRIGger:A:SETHOLDLOGICVAL:DCH<x>_D<x>
TRIGger:A:TIMEOut:POLarity
TRIGger:A:TIMEOut:SOUrce
TRIGger:A:TIMEOut:TIMe
TRIGger:A:TYPe
TRIGger:A:UPPerthreshold:CH<x>
TRIGger:AUXLevel
TRIGger:HYSTeresis:USER:STATe
TRIGger:HYSTeresis:USER:VALue
TRIGger:STATE?
*TST?
UNDO
UNLock
USBDevice:CONFigure
VERBose
VERTical:DESKew:FROM:CUSTOMPROPAgation
VERTical:DESKew:FROM:SOUrce
VERTical:DESKew:STATIC
VERTical:DESKew:TO:CUSTOMPROPAgation
VERTical:DESKew:TO:SOUrce
VXI:ENAble
VXI:PORT:HIGH
VXI:PORT:LOW
*WAI
WAVFrm?
WFMOutpre?
WFMOutpre:ASC_Fmt?
WFMOutpre:BIT_Nr
WFMOutpre:BN_Fmt
WFMOutpre:BYT_Nr
WFMOutpre:BYT_Or
WFMOutpre:CENTERFREQuency?
WFMOutpre:DOMain?
WFMOutpre:ENCdg
WFMOutpre:NR_Pt?
WFMOutpre:PT_Fmt?
WFMOutpre:PT_Off?
WFMOutpre:PT_ORder?
WFMOutpre:RESample
WFMOutpre:SPAN?
WFMOutpre:WFId?
WFMOutpre:WFMTYPe?
WFMOutpre:XINcr?
WFMOutpre:XUNit?
WFMOutpre:XZEro?
WFMOutpre:YMUlt?
WFMOutpre:YOFf?
WFMOutpre:YUNit?
WFMOutpre:YZEro?
""".strip().splitlines()

# ─────────────────────────────────────────────────────────────────────────────
# Paths  (edit if your layout differs)
# ─────────────────────────────────────────────────────────────────────────────
ROOT        = Path(__file__).resolve().parent.parent
SOURCE_JSON = ROOT.parent / "mso_2_4_5_6_7.json"          # one level up from project
OUTPUT_JSON = ROOT.parent / "mso2.json"
MISSING_TXT = ROOT.parent / "mso2_missing.txt"

# ─────────────────────────────────────────────────────────────────────────────

def normalise(header: str) -> str:
    """Lower-case, strip trailing ?, collapse whitespace."""
    return re.sub(r"\s+", "", header.strip().lower().rstrip("?"))


def main():
    if not SOURCE_JSON.exists():
        print(f"ERROR: source not found: {SOURCE_JSON}")
        sys.exit(1)

    print(f"Loading {SOURCE_JSON} …")
    with open(SOURCE_JSON, encoding="utf-8", errors="replace") as f:
        source = json.load(f)

    # Build a lookup: normalised_header -> command object
    lookup: dict[str, list] = {}
    for grp in source.get("groups", {}).values():
        for cmd in grp.get("commands", []):
            scpi = cmd.get("scpi", "")
            key  = normalise(scpi)
            lookup.setdefault(key, []).append(cmd)

    # Also index by _manualEntry.header
    for grp in source.get("groups", {}).values():
        for cmd in grp.get("commands", []):
            me = cmd.get("_manualEntry") or {}
            h  = me.get("header", "")
            if h:
                lookup.setdefault(normalise(h), []).append(cmd)

    # Match requested headers
    want       = [h.strip() for h in MSO2_HEADERS if h.strip()]
    found_cmds = []
    missing    = []

    for header in want:
        key = normalise(header)
        if key in lookup:
            # de-dup: same cmd may be indexed under multiple keys
            for c in lookup[key]:
                if c not in found_cmds:
                    found_cmds.append(c)
        else:
            missing.append(header)

    # Re-group found commands by their group field
    out_groups: dict[str, dict] = {}
    for cmd in found_cmds:
        grp_name = cmd.get("group", "Miscellaneous")
        if grp_name not in out_groups:
            out_groups[grp_name] = {"name": grp_name, "description": "", "commands": []}
        out_groups[grp_name]["commands"].append(cmd)

    output = {
        "version": "2.0",
        "manual":  "MSO2 Series Programmer Manual",
        "metadata": {
            "total_commands": len(found_cmds),
            "total_groups":   len(out_groups),
            "source":         "filtered from mso_2_4_5_6_7.json",
        },
        "groups": out_groups,
    }

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"\nOK  Written {len(found_cmds)} commands across {len(out_groups)} groups -> {OUTPUT_JSON}")

    if missing:
        with open(MISSING_TXT, "w", encoding="utf-8") as f:
            f.write("\n".join(missing))
        print(f"WARN   {len(missing)} headers NOT found in source -> {MISSING_TXT}")
        print("    These need to be added manually (MSO2-exclusive commands not in MSO 4/5/6/7).")
    else:
        print("OK  All headers matched — no missing commands.")

    # Summary by group
    print("\nGroup breakdown:")
    for gname, grp in out_groups.items():
        print(f"  {gname}: {len(grp['commands'])} commands")


if __name__ == "__main__":
    main()
